- name: Setup wordpress
  hosts: all

  tasks:
    - name: Provide apache+php
      package:
        name:
          - apache2
          - libapache2-mod-php8.1
          - php8.1-pgsql
          - php8.1-mysql
        state: present
        cache_valid_time: 3600

    - name: Ensure apache is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure adminer dir
      file:
        path: "{{ adminer_target_dir }}"
        state: directory
        mode: 0755

    - name: Provide adminer bundle
      get_url:
        url: "{{ adminer_source }}"
        dest: "{{ adminer_target_dir }}/adminer.php"
        checksum: "{{ adminer_checksum }}"
        mode: 0644

    - name: Remove stale index.html
      file:
        dest: /var/www/html/index.html
        state: absent

    - name: Provide index.php
      copy:
        content: |
          <?php
          define('ADMINER_DIR', '{{ adminer_target_dir }}');
          include ADMINER_DIR . '/adminer.php';
          ?>
        dest: /var/www/html/index.php

